### ISSUE TITLE
Add support for arm64 linux

### ISSUE THREAD

**Issue by navels** [vovayartsev/wkhtmltopdf-installer-ruby#10] opened 2022-01-28 17:33 UTC
PR: https://github.com/vovayartsev/wkhtmltopdf-installer-ruby/pull/9

**Comment by navels** [comment] 2022-02-15 18:30
@vovayartsev are you available?

**Comment by navels** [comment] 2022-03-26 18:44
@vovayartsev

**Comment by jhuckabee** [comment] 2022-06-08 18:49
ping @vovayartsev

**Comment by vovayartsev** [comment] 2022-06-08 21:31
Thank you @navels (and @jhuckabee for the reminder 👍 )
Looking into the PR now

**Comment by vovayartsev** [comment] 2022-06-08 21:48
Just uploaded the binary to the Releases and merged the PR.
If someone could confirm that the`master` branch works on arm64 linux - I'll release it to Rubygems.

Thanks again for your contribution @navels 🙏

**Comment by navels** [comment] 2022-06-08 23:41
Thanks!  Seems I was mistaken about the binary, I actually need

https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_arm64.deb

i.e., debian buster, not ubuntu bionic.

**Comment by vovayartsev** [comment] 2022-06-09 07:19
👌 I've just put a new binary to Releases. Does it work now?

**Comment by jhuckabee** [comment] 2022-06-09 13:25
I can confirm the installing from master works for me on debian stretch. Thanks for the update @vovayartsev

**Comment by navels** [comment] 2022-06-09 15:33
Success, thanks!

**Comment by vovayartsev** [comment] 2022-06-11 11:03
Thanks for confirming!
Released to [Rubygems](https://rubygems.org/gems/wkhtmltopdf-installer/versions/0.12.6.3)

**Closed by vovayartsev** 2022-06-11 11:03 UTC
